#!/usr/bin/env python3
"""Legacy INCAR generator entry point.

This script is kept as a lightweight compatibility wrapper around
``brain.incar`` so older ``in.py`` workflows continue to work.
"""

import sys
from pathlib import Path

repo_root = Path(__file__).resolve().parent.parent
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from actions_py.bootstrap import ensure_repo_root

ensure_repo_root()

from brain import incar as brain_incar


def main(argv: list[str] | None = None) -> int:
    tasks = brain_incar.parse_tasks(argv)
    try:
        brain_incar.build_incar(tasks)
    except brain_incar.UnsupportedTasksError as exc:
        print(exc, file=sys.stderr)
        return 1

    task_msg = f" (tasks: {' '.join(tasks)})" if tasks else ""
    print(f"INCAR generated by in.py{task_msg}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
