#!/usr/bin/env python3
import sys
from pathlib import Path

"""Generate POTCAR files.

Uses the `brain.potcar` helpers when available, falling back to a local
`potcar` module for backward compatibility.
"""
import os

# Ensure repo root is on sys.path so 'brain' package can be imported when
# the script is executed from elsewhere (e.g. ~/bin in PATH).
repo_root = Path(__file__).resolve().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from actions_py.bootstrap import ensure_repo_root

ensure_repo_root()

try:
    from brain.potcar import concatenate, read_potcar
except Exception:
    # fallback for legacy module (potcar.py in repo root)
    try:
        from potcar import concatenate, read_potcar
    except Exception as e:
        print('Could not import POTCAR helpers (brain.potcar or potcar).', e)
        raise

# Prefer a normal calculation POSCAR.  For an NEB calculation, use the first
# image (00/POSCAR) and still write the combined POTCAR in the NEB root.
poscar_path = None
if os.path.isfile('POSCAR'):
    poscar_path = Path('POSCAR')
elif os.path.isfile(Path('00') / 'POSCAR'):
    poscar_path = Path('00') / 'POSCAR'

if len(sys.argv[:]) == 1:
    # Auto mode by reading the POSCAR
    if poscar_path is not None:
        print(f'POTCAR is generated by reading {poscar_path}!\n')
        with poscar_path.open('r') as f:
            lines = f.readlines()

        # Default: element symbols on line 6 (index 5)
        if len(lines) > 5:
            ele_line = lines[5].strip()
        else:
            ele_line = ''

        ele_list = ele_line.split() if ele_line else []

        # VASP4 / ASE style POSCAR where the first line lists elements
        if not ele_list or ele_list[0].isdigit():
            if lines:
                print('\nPOSCAR Format: VASP4 or no explicit element line\n')
                ele_list = lines[0].strip().split()

        if not ele_list:
            print('Could not determine elements from POSCAR; aborting.')
            sys.exit(1)

        concatenate(ele_list)
        read_potcar('POTCAR')
    else:
        print('%s' % ('%' * 40))
        print('\n' + 'WARNING!!!' * 3)
        print('\nPOTCAR CANNOT be automatically generated because neither '
              'POSCAR nor 00/POSCAR exists!!!\n')
        print('But you can make it by using command below:\n')
        print('  pp.py element1 element2 ....\n')
        print('%s' % ('%' * 40))

if len(sys.argv) > 1:
    # Make POTCAR manually.
    ele_list = sys.argv[1:]
    concatenate(ele_list)
    read_potcar('POTCAR')
