### Q_robot
export ROBOT=$HOME/bin/qrob
for d in "$ROBOT"/actions_*; do
  [ -d "$d" ] || continue
  PATH="$PATH:$d"
done
export PATH="$PATH:$ROBOT/friends/vtstscripts-1040"
export PYTHONPATH=$PYTHONPATH:$ROBOT/brain
